server:
  port: 9001
  servlet:
    context-path: /authroization-service

spring:
  application.name: authroization-service
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    show-sql: true # for local testing
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc.batch_size: 45
        order_inserts: true
        order_updates: true
        jdbc.fetch_size: 1000
        jdbc.batch_versioned_data: true
database:
  url: jdbc:postgresql://localhost:5432/csp_dev?useSSL=false
  username: postgres
  password: postgres
  packages-to-scan: # packages for entities
    - com.csp.authorization.**.*
  hikari-properties:
    autoCommit: false
    poolName: csp_pool
    maxPoolSize: 20
    maxIdleTime: 10000