version: '3'
services:
  eureka-service:
    build: ./csp-eureka-service
    ports:
      - "8998:8998"
    networks:
      -  microservice-network
  config-service:
    build: ./csp-config-service
    ports:
      - "8999:8999"
    environment:
#      - CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/smitJadhav/csp-config
#      - CLOUD_CONFIG_SERVER_GIT_USER=smitjadhav10@gmail.com
#      - CLOUD_CONFIG_SERVER_GIT_private_key_file=../../private_key
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8998/eureka
#      - DATABASE_URL=jdbc:jdbc:postgresql://192.168.1.24:5432/csp_dev?useSSL=false
    networks:
      -  microservice-network
  gateway-service:
    build: ./csp-gateway-service
    ports:
      - "9000:9000"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8998/eureka
      - DATABASE_URL=jdbc:jdbc:postgresql://192.168.1.24:5432/csp_dev?useSSL=false
    networks:
      -  microservice-network
  authorization-service:
    build: ./csp-authorization-service
    ports:
      - "9001:9001"
    depends_on:
      - eureka-service
      - config-service
    environment:
#      - DATABASE_URL=jdbc:postgresql://172.21.240.1:5432/csp_dev?useSSL=false
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8998/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8999
      - DATABASE_URL=jdbc:jdbc:postgresql://192.168.1.24:5432/csp_dev?useSSL=false
    networks:
      -  microservice-network
  admin-service:
    build: ./csp-admin-service
    ports:
      - "9002:9002"
    depends_on:
      - eureka-service
      - config-service
    environment:
#      - DATABASE_URL=jdbc:postgresql://172.21.240.1:5432/csp_dev?useSSL=false
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8998/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8999
      - DATABASE_URL=jdbc:postgresql://192.168.1.24:5432/csp_dev?useSSL=false
    networks:
      -  microservice-network
  user-service:
    build: ./csp-user-service
    ports:
      - "9003"
    depends_on:
      - eureka-service
      - config-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8998/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8999
      - DATABASE_URL=jdbc:jdbc:postgresql://192.168.1.24:5432/csp_dev?useSSL=false
    networks:
      -  microservice-network
#  start_dependencies:
#    image: dadarek/wait-for-dependencies
#    depends_on:
#      - eureka-service
#      - config-service
#    command: eureka-service:8998 config-service:8999
#    networks:
#      -  microservice-network
networks:
  microservice-network:
    driver: bridge