server:
  port: 8999

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:///D:\Projects\Java\CSP\csp-config
          uri: https://github.com/smitJadhav/csp-config

eureka:
  client:
#    eureka-server-port: 8998
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8998/eureka
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
