server:
  port: 9000

spring:
  application:
    name: gateway-service

zuul:
  prefix: /api
  routes:
    authorization-service:
      sensitiveHeaders:
      path: /authorization-service/**
      serviceId: authorization-service
    admin-service:
      sensitiveHeaders:
      path: /admin-service/**
      serviceId: admin-service
    user-service:
      sensitiveHeaders:
      path: /user-service/**
      serviceId: user-service

eureka:
  client:
#    eureka-server-port: 8998
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8998/eureka