server:
  port: 8998

spring:
  application:
    name: eureka-service

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-service:8998/eureka
    healthcheck:
      enabled: true