package com.csp.user.domain;

import com.csp.model.Gender;
import com.csp.user.domain.base.AbstractAuditingEntity;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;

@Table(name = "user_details")
@Entity
@Getter
@Setter
public class User extends AbstractAuditingEntity {

    private String userName;
    private String firstName;
    private String middleName;
    private String lastName;
    private String password;
    private String email;
    private String phone;
    private boolean isNonLocked;
    private boolean isActive;
    private boolean isPasswordAutogenerated;
    private Integer numberOfAttempts;
    private String statusChangeReason;
    @Enumerated(EnumType.STRING)
    private Gender gender;
    @ManyToOne
    private Role role;
}
