package com.csp.user.service;

import com.csp.user.domain.Role;
import com.csp.user.domain.User;
import com.csp.user.mapper.UserMapper;
import com.csp.user.model.UserDTO;
import com.csp.user.repository.RoleRepository;
import com.csp.user.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class UserServiceImpl implements UserService {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private RoleRepository roleRepository;

    @Autowired
    private UserMapper userMapper;

    @Override
    @Transactional
    public Long saveUser(UserDTO userDTO) {
        User user = userMapper.mapUserDTOToUSer(userDTO);
        Role role = roleRepository.findById(userDTO.getRoleId()).get();
        user.setRole(role);
        //TODO : Add encrypted password generation logic
        user.setPassword("Password@123");
        user.setActive(true);
        user.setNonLocked(true);
        user.setPasswordAutogenerated(true);
        return userRepository.save(user).getId();
    }

    @Override
    @Transactional
    public UserDTO findUser(Long id) {
        User user = userRepository.findById(id).get();
        return userMapper.mapUserToUSerDTO(user);
    }
}
