server:
  port: 9002

springdoc:
  api-docs:
    path: /api-docs

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: admin-service
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc.batch_size: 45
        order_inserts: true
        order_updates: true
        jdbc.fetch_size: 1000
        jdbc.batch_versioned_data: true
database:
  url: jdbc:postgresql://localhost:5432/csp_dev?useSSL=false
  username: postgres
  password: postgres
  packages-to-scan: # packages for entities
    - com.csp.admin.**.*
  hikari-properties:
    autoCommit: false
    poolName: csp_pool
    maxPoolSize: 20
    maxIdleTime: 10000

jwt.secret: itsasecret

oauth:
  resource:
    server:
      enable : true
  login.max.attempts: 3

eureka:
  client:
    eureka-server-port: 8761
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
